In [1]:
import pandas as pd
from bs4 import BeautifulSoup
import requests

# 1. 가로등 데이터

In [89]:
url_street = 'http://openapi.jeonju.go.kr/rest/streetlamp/getStreetlamp?authApiKey='
open_api_key = '30NUDEQ1MBHnAJ6uehvw8Bman579Pq9xYEkMgIYWL1cYKLaNtfP1I4eLSZVmTnDz2juz9RaCLQKoUbWRBYcIYQ%3D%3D'
pagesize = '&pageSize=1000'

In [90]:
total_counts = 14935
page_size = 1000
pages = int(total_counts / page_size) + 1
streetlamp = []

for i in range(pages):
    print('getting data from page %s of page %s'%(i+1,pages))
    open_url = url_street + open_api_key + '&startPage=' + str(i+1) + pagesize
    
    req = requests.get(open_url)
    html = req.text
    soup = BeautifulSoup(html, 'html.parser')
    soup_list = soup.find_all('list')
    
    var_lists = ['basedate','boxnm','lampcnt','polenum','posx','posy','seq']
    
    for n in range(len(soup_list)):
        a=[]
        for var in var_lists:
            found_var = soup_list[n].find_all(var)
            found_var = [x.text for x in found_var]
            a += found_var
            
        streetlamp.append(a)

getting data from page 1 of page 15
getting data from page 2 of page 15
getting data from page 3 of page 15
getting data from page 4 of page 15
getting data from page 5 of page 15
getting data from page 6 of page 15
getting data from page 7 of page 15
getting data from page 8 of page 15
getting data from page 9 of page 15
getting data from page 10 of page 15
getting data from page 11 of page 15
getting data from page 12 of page 15
getting data from page 13 of page 15
getting data from page 14 of page 15
getting data from page 15 of page 15

In [91]:
df1 = pd.DataFrame(streetlamp)
df1

                0       1  2  3           4          5      6
0      2015-08-26   흑석로01  1  8  127.150337  35.802458  14935
1      2015-08-26   흑석로01  1  7  127.150302  35.801953  14934
2      2015-08-26   흑석로01  1  6  127.150561  35.801543  14933
3      2015-08-26   흑석로01  1  5  127.150776   35.80116  14932
4      2015-08-26   흑석로01  1  4  127.150823   35.80069  14931
...           ...     ... .. ..         ...        ...    ...
14930  2015-08-26  가련산로01  2  5   127.10944  35.841589      5
14931  2015-08-26  가련산로01  2  4   127.10988  35.841339      4
14932  2015-08-26  가련산로01  2  3  127.109787  35.841054      3
14933  2015-08-26  가련산로01  2  2  127.109582  35.840878      2
14934  2015-08-26  가련산로01  2  1  127.109411  35.840694      1

[14935 rows x 7 columns]

# 2. 보안등 데이터

In [92]:
url_safty = 'http://openapi.jeonju.go.kr/rest/saftylight/getSaftylight?authApiKey='
open_api_key = '30NUDEQ1MBHnAJ6uehvw8Bman579Pq9xYEkMgIYWL1cYKLaNtfP1I4eLSZVmTnDz2juz9RaCLQKoUbWRBYcIYQ%3D%3D'
pagesize = '&pageSize=1000'

In [93]:
var_lists = ['bdong','bpolenum','basedate','concompany','detailaddr','estatype',
             'flashtype','hdong','ipolenum','insdate','kepcocustom','lampcap1',
             'lampcap2','lampcap3','lamplife','lamptype1','lamptyp2','lamptype3',
             'lightcnt','lightpole','lighttype','linenum','lotnumber','manageno',
             'newaddr','posx','posy','seq','specialnote','useamt']

In [94]:
total_counts = 10218
page_size = 1000
pages = int(total_counts / page_size) + 1
saftylight = []

for i in range(pages):
    print('getting data from page %s of page %s'%(i+1,pages))
    open_url = url_safty + open_api_key + '&startPage=' + str(i+1) + pagesize
    
    req = requests.get(open_url)
    html = req.text
    soup = BeautifulSoup(html, 'html.parser')
    soup_list = soup.find_all('list')

    for n in range(len(soup_list)):
        a=[]
        for var in var_lists:
            found_var = soup_list[n].find_all(var)
            found_var = [x.text for x in found_var]
            a += found_var
            
        saftylight.append(a)

getting data from page 1 of page 11
getting data from page 2 of page 11
getting data from page 3 of page 11
getting data from page 4 of page 11
getting data from page 5 of page 11
getting data from page 6 of page 11
getting data from page 7 of page 11
getting data from page 8 of page 11
getting data from page 9 of page 11
getting data from page 10 of page 11
getting data from page 11 of page 11

In [95]:
df2 = pd.DataFrame(saftylight)
df2

,0,1,2,3,4,5,6,7,8,9,...,19,20,21,22,23,24,25,26,27,28
0,상림동,,2018-01-22,삼흥엔지니어링(주),진입로,신설,GPS,효자4동,0329Z342,2016-06-25,...,가오스,,540,효자동1650,원상림길125-14,127.0749901,35.8146116,10218,,81
1,상림동,,2018-01-22,삼흥엔지니어링(주),진입로,신설,GPS,효자4동,0329Z232,2016-06-25,...,가오스,,540,효자동1649,원상림길125-14,127.0749901,35.8146116,10217,,81
2,상림동,,2018-01-22,삼흥엔지니어링(주),진입로,신설,GPS,효자4동,0329Z221,2016-06-25,...,가오스,,540,효자동1648,원상림길125-14,127.0749901,35.8146116,10216,,81
3,상림동,,2018-01-22,삼흥엔지니어링(주),진입로,신설,GPS,효자4동,0329Z123,2016-06-25,...,가오스,,540,효자동1647,원상림길125-14,127.0749901,35.8146116,10215,,81
4,상림동,,2018-01-22,삼흥엔지니어링(주),진입로,신설,GPS,효자4동,0329Y811,2016-06-25,...,가오스,,540,효자동1646,원상림길125-14,127.0749901,35.8146116,10214,,81
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10213,금암동,0630Y468,2018-01-22,,,신설,GPS,금암1동,0630Y553,2016-02-16,...,가오스,,453-1,금암동917,팔달로373-1,127.136591,35.8334338,5,,0
10214,,,2018-01-22,(유)일동이엔지,,신설,GPS,금암1동,0630Q152,2015-10-14,...,가오스,,714-6,금암동916,떡전4길8,127.1287601,35.8383327,4,,0
10215,금암동,,2018-01-22,(유)일동이엔지,,신설,GPS,금암1동,0630G002,2015-06-30,...,가오스,,728-254,금암동915,금암1길11,127.1340338,35.8400664,3,,0
10216,금암동,,2018-01-22,(유)일동이엔지,,신설,GPS,금암1동,0630G161,2015-06-25,...,가오스,,628-18,금암동914,삼송1길32,127.1346474,35.84271,2,,0
10217,금암동,0630Y194,2018-01-22,(주)이테크,,기설,,금암1동,0630Y081,2017-06-06,...,가오스,,460-27,금암동137,가리내로 22-4,127.133606,35.834741,1,,81

# 3. csv로 내보내기

In [97]:
df1.to_csv('C:/Users/user/python/local/Jeonju/data/streetlamp.csv',encoding = 'euc-kr',index=False)
df2.to_csv('C:/Users/user/python/local/Jeonju/data/saftylamp.csv',encoding = 'euc-kr',index=False)